{% set name = "azure-monitor-opentelemetry-exporter" %}
{% set version = "1.0.0b42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure_monitor_opentelemetry_exporter-{{ version }}.tar.gz
  sha256: d35b60e0404446932e31e3a0b1c2202e47e9b78f91bb24110bd164aa62c5bb87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - azure-storage-blob
    - django
    - fastapi
    - flask
    - isodate
    - psycopg2
    - requests
    - uvicorn
    - python >={{ python_min }}
    - azure-core <2.0.0,>=1.28.0
    - azure-identity >=1.17,<2.dev0
    - fixedint ==0.1.6
    - msrest >=0.6.10
    - opentelemetry-api ~=1.35
    - opentelemetry-sdk ~=1.35
    - psutil <8,>=5.9

test:
  imports:
    - azure.monitor.opentelemetry.exporter
    - azure.monitor.opentelemetry.exporter._generated
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter
  summary: Microsoft Azure Monitor Opentelemetry Exporter Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-api
